config/routes.rb
Epuka::Application.routes.draw do
  root :to => 'home#index'

  resources :diseases
	resources :home, :only => [:index]
	resources :contacts, :only => [:index, :new, :create, :show, :destroy]
	get "feed/rss"
	resources :domains
  resources :posts

  authenticated :user do
  	root :to => 'home#index'
	end



  devise_for :users
	resources :users, :only => [:show, :index]
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  attr_accessible :more_info, :name

	validates_presence_of :name, :more_info
	validates_uniqueness_of :name

	belongs_to :user
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_filter :authenticate_user!, :except => [ :index, :show ]
	before_filter :only_allow_admin, :only => [ :destroy, :edit, :new ]

  def index
    @domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @domains }
    end
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.json
  def new
    @domain = Domain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(params[:domain])
		@domain.user_id = current_user

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render json: @domain, status: :created, location: @domain }
      else
        format.html { render action: "new" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.json
  def update
    @domain = Domain.find(params[:id])

    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to domains_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= simple_form_for @domain, :html => { :class => 'form-horizontal' } do |f| %>
	<%= f.error_notification %>

  <%= f.input :name, :placeholder => "e.g. gmail.com" %>
  <%= f.input :more_info, :placeholder => "more info about the organization", :input_html => { :style => "height: 35px" } %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                domains_path, :class => 'btn' %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<%- model_class = @domain.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/domains/index.html.erb
<%- model_class = Domain.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr class="breadcrumb">
      <th><%= model_class.human_attribute_name(:domain_name) %></th>
      <th><%= model_class.human_attribute_name(:more_info) %></th>
			<% if user_signed_in? %>
					<% if current_user.has_role? :admin %>
      			<th><%=t '.actions', :default => t("helpers.actions") %></th>
					<% end %>
			<% end %>

    </tr>
  </thead>
  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= link_to domain.name, domain_path(domain) %></td>
        <td><%= domain.more_info %></td>
        <td>
					<% if user_signed_in? %>
						<% if current_user.has_role? :admin %>
				      <%= link_to t('.edit', :default => t("helpers.links.edit")),
				                  edit_domain_path(domain), :class => 'btn btn-mini' %>
				      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
				                  domain_path(domain),
				                  :method => :delete,
				                  :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
				                  :class => 'btn btn-mini btn-danger' %>
						<% end %>
					<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
					<% if current_user.has_role? :admin %>
						<%= link_to t('.new', :default => t("helpers.links.new")),
												new_domain_path,
												:class => 'btn btn-primary' %>
	<% end %>
<% end %>

app/views/domains/new.html.erb
<%- model_class = @domain.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/domains/show.html.erb
<%- model_class = @domain.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<div class="well" >
	<p>
		<strong><%= model_class.human_attribute_name(:registered_by) %>:</strong><br>
		<%= User.find(@domain.user_id).name %>
	</p>
	<p>
		<strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
		<%= @domain.name %>
	</p>
	<p>
		<strong><%= model_class.human_attribute_name(:more_info) %>:</strong><br>
		<%= @domain.more_info %>
	</p>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              domains_path, :class => 'btn btn-primary'  %>
	<% if user_signed_in? %>
			<% if current_user.has_role? :admin %>
				<%= link_to t('.edit', :default => t("helpers.links.edit")),
						        edit_domain_path(@domain), :class => 'btn' %>
				<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
						        domain_path(@domain),
						        :method => 'delete',
						        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
						        :class => 'btn btn-danger' %>
		<% end %>
	<% end %>
</div>