config/routes.rb
Epuka::Application.routes.draw do
  root :to => 'home#index'

  resources :diseases
	resources :home, :only => [:index]
	resources :contacts, :only => [:index, :new, :create, :show, :destroy]
	get "feed/rss"
	resources :domains
  resources :posts

  authenticated :user do
  	root :to => 'home#index'
	end



  devise_for :users
	resources :users, :only => [:show, :index]
end

app/views/layouts/_about.html.erb
<div class="span3">
	<!--<a href="#" id="livilyChatLink" class="livilyChatButton ClickdeskChatLink" onclick="return false;"></a>-->
	<script type="text/javascript"><!--
  // RSS Subscribe Feed URL.
  rssbm_subscribeFeed  = "http://epuka.herokuapp.com/feed/rss";
  // Button Image URL.
  rssbm_buttonImageUrl = "http://farm8.staticflickr.com/7075/7189291898_8a32a397f3_m.jpg";
  // Set this to yes if you put your image on the right side of
  // the page and the drop down menu goes outside the window.
  rssbm_imgRightSide   = "no";
//-->
</script>
<script type="text/javascript" src="http://www.seocentro.com/bookmark-rss/rss.js"></script>

<h2>About Epuka</h2>
  <p>The Epuka Disease Reporting System (EDRS) provides real-time secured
access for state and local public health practitioners to report infectious diseases.
EDRS allows local health departments with jurisdictional responsibility and relevant ODH
program staff to have immediate access to infectious disease reports on a 24/7/365
basis for disease control and disease surveillance purposes.
This assures cases of significant public health importance receive immediate attention
and public health response.</p>

		<h3>Our users?</h3>
		<p>Anyone can use this system. Infection control professionals, individual health care
		providers and laboratories can also become EDRS users
		for infectious disease reporting purposes.</p></br>
		<%= render 'layouts/other/g_search' %>
</div>

app/views/layouts/_chat.html.erb
<!-- ClickDesk - <a href='http://www.clickdesk.com'> Live Chat Service </a> for websites -->
<script type='text/javascript'>
var _glc =_glc || [];
_glc.push('ag9jb250YWN0dXN3aWRnZXRyEAsSB3dpZGdldHMYjs6wAgw');
var glcpath = (('https:' == document.location.protocol) ? 'https://contactuswidget.appspot.com/livily/browser/' : 'http://gae.clickdesk.com/livily/browser/');
var glcp = (('https:' == document.location.protocol) ? 'https://' : 'http://');
var glcspt = document.createElement('script'); glcspt.type = 'text/javascript'; glcspt.async = true;glcspt.src = glcpath + 'livechat.js';
var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(glcspt, s);
</script><noscript><p><a href='http://gae.clickdesk.com/clickdeskchat.jsp?widget_id=ag9jb250YWN0dXN3aWRnZXRyEAsSB3dpZGdldHMYjs6wAgw' >HelpDesk Software</a></p></noscript>

app/views/layouts/_footer.html.erb
<footer class="footer" style="background-color:#222222;">
		<span class="f1"></span>
		  <span class="f2"></span>
		  <span class="f3"></span>
		  <span class="f4"></span>
		  <span class="f5"></span>
    <div class="container" style="margin:0 auto;">
        <div class="row">
            <div class="span2 offset2">
                <h4>Company</h4>
                <ul>
                    <li><a href="">About Us</a></li>
                    <li><%= link_to('Contact Us', new_contact_path)  %></li>
										<li><%= link_to('Registered Domains', domains_path)  %></li>
										<li><a href="http://www.flickr.com/photos/78329428@N02/" title="Flickr" target="_blank">Flickr</a></li>
                </ul>
            </div>
            <div class="span2 offset1">
                <h4>Resource</h4>
                <ul>
                    <li>
											<a href="https://github.com/Banta/epuka/wiki"title="Documentation" target="_blank">Documentation</a>
										</li>
                    <li><a href="">FAQ</a></li>
                    <li>
											<a href="https://github.com/Banta/epuka/issues"title="Issues" target="_blank">Issues</a>
										</li>
                </ul>
            </div>
            <div class="span2 offset1">
                <h4>Connect</h4>
                <ul>
                    <li><a href="http://www.facebook.com/pages/Epuka/165504110244670" title="Facebook" target="_blank">Facebook</a></li>
                    <li><a href="https://twitter.com/#!/EpukaDRS"title="Twitter" target="_blank">Twitter</a></li>
                    <li><a href="" title="LinkedIn" target="_blank">LinkedIn</a></li>
                    <li><a href="" title="Google+" target="_blank">Google+</a></li>
                    <li><a href="http://epuka.herokuapp.com/feed/rss" title="RSS" target="_blank">RSS</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_g_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31339087-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Epuka", root_path, :class => 'brand' %>
<div class="nav-collapse">
	<ul class="nav">
			<li>
		  <%= link_to('Diseases', diseases_path)  %>
		  </li>
			<li>
				<a href="http://www.ehealth.or.ke/facilities/latestfacilities.aspx"title="e-Health" target="_blank">e-Health</a>
			</li>
			<li>
				<a href="http://epuka.herokuapp.com/posts" title="Blogs" target="_blank">Blogs</a>
			</li>
			<li>
				<a data-toggle="modal" href="#myModal">Gallery</a>
			</li>
			<li>
				<a href="https://github.com/Banta/epuka"title="Contribute" target="_blank">Contribute</a>
			</li>
			<li>
		  <%= link_to('Contact Us', new_contact_path)  %>
		  </li>
	</ul>
	<%= form_tag root_path, :class=>"navbar-search pull-left", :method => :get do %>
					<%= text_field_tag :search, params[:search], :class=>"search-query", :placeholder=>"Search the location" %>
	<% end %>
	<ul class="nav pull-right">
		<% if user_signed_in? %>
		  <li>
		  	<%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
		  </li>
		<% else %>
		  <li>
		  <%= link_to('Login', new_user_session_path)  %>
		  </li>
		<% end %>
		<% if user_signed_in? %>
		  <li>
		  <%= link_to('Edit account', edit_user_registration_path) %>
		  </li>
		  <% if current_user.has_role? :admin %>
		    <li>
		    <%= link_to('Admin', users_path) %>
		    </li>
		  <% end %>
		<% else %>
		  <li>
		  	<%= link_to('Sign up', new_user_registration_path)  %>
		  </li>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Epuka" %></title>
    <meta name="description" content="The Epuka Disease Reporting System (EDRS) provides real-time secured access for state and local public health practitioners to report infectious diseases. EDRS allows local health departments with jurisdictional responsibility and relevant ODH program staff to have immediate access to infectious disease reports on a 24/7/365 basis for disease control and disease surveillance purposes. This assures cases of
    significant public health importance receive immediate attention and public health response.">
    <meta name="author" content="Bernard Banta, Ruby On Rails Developer">
    <meta name="keywords"
   content="epuka,benard banta,cliff anami,belinda atieno, disease monitoring, disease reporting, EDRS" />
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
		<%= render 'layouts/other/javascripts' %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
		<%= render 'layouts/g_analytics' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
        	</a>
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
		<div id="wrap">
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span9">
              <%= render 'layouts/messages' %>
              <%= yield %>
							<%= render 'home/gallery' %>
							<%= yield :scripts %>
            </div>
						<%= render 'layouts/about' %>
          </div>
					<%#= render 'layouts/footer' %>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
		</div>
	<%= render 'layouts/chat' %>
	<%= render 'layouts/footer' %>
  </body>
</html>